#!/usr/bin/env node
// Pulls Vital.site's frontend/ui/ component set from vital-sandbox.com/cdn/ui/
// into shared/ui/ (repo root) before dev/build for either app.
//
// Component list is discovered from the CDN manifest (generated by
// Vital.site/shared/sync.js) — no hardcoded FILES array to maintain.
//
// shared/ui/ is generated and gitignored; Vital.site/frontend/ui/ remains
// the single source of truth.

import fs   from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CDN_BASE   = process.env.VITAL_UI_CDN ?? 'https://vital-sandbox.com/cdn/ui';
const TARGET_DIR = path.resolve(__dirname, '../shared/ui');

async function fetch_text(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return res.text();
}

async function load_file_list() {
  const url = `${CDN_BASE}/manifest.json`;
  try {
    const raw = await fetch_text(url);
    const manifest = JSON.parse(raw);
    if (Array.isArray(manifest.files) && manifest.files.length > 0) {
      console.log(`[sync-ui] manifest: ${manifest.files.length} files`
        + (manifest.components ? ` (${manifest.components.length} components)` : ''));
      return manifest.files;
    }
    if (Array.isArray(manifest.components)) {
      const files = [];
      for (const c of manifest.components) {
        for (const f of c.files || []) files.push(`${c.name}/${f}`);
      }
      if (files.length) {
        console.log(`[sync-ui] manifest: ${files.length} files (${manifest.components.length} components)`);
        return files;
      }
    }
    throw new Error('manifest.json missing files/components');
  }
  catch (err) {
    console.warn(`[sync-ui] manifest fetch failed (${err.message}); using fallback list`);
    return [];
  }
}

async function main() {
  const files = await load_file_list();
  let failed = false;
  let ok = 0;

  for (const rel_path of files) {
    const dest = path.join(TARGET_DIR, rel_path);
    try {
      const text = await fetch_text(`${CDN_BASE}/${rel_path}`);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, text, 'utf8');
      console.log(`  synced: ${rel_path}`);
      ok++;
    } 
    catch (err) {
      failed = true;
      console.warn(`[sync-ui] failed to fetch ${rel_path}: ${err.message}`);
    }
  }

  if (failed && !fs.existsSync(path.join(TARGET_DIR, 'card/index.jsx'))) {
    console.error('[sync-ui] no shared/ui files available locally and fetch failed — aborting build');
    process.exit(1);
  }
  console.log(`[sync-ui] done (${ok}/${files.length})`);
}

main();
