name: Release Packages

on:
  release:
    types: [published]

jobs:
  release:
    name: Create Packages
    runs-on: ubuntu-latest

    steps:
    - name: Checking Repository
      uses: actions/checkout@v3

    - name: Creating Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org

    - name: Building Package
      run: |
        npm install

    - name: Publishing Package
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
